version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.database
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/vps-3503468-x.dattaweb.com/certbot:/var/www/certbot
    ports:
      - 1337:80
      - 8443:443  # Para HTTPS
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: